#!/usr/bin/env bash

# Copyright 2015 gisphm <phmfk@hotmail.com>
# Author: gisphm <phmfk@hotmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

build_dir=~/.vim/build
src_dir=~/.vim/build/snippets
snippets_dir=~/.vim/neosnippets
list_file=~/.vim/scripts/snippets_list
snippets_list=($(cat $list_file))

[[ -d $build_dir ]] && rm -rf $build_dir

mkdir -p $build_dir

git clone --depth=1 https://github.com/honza/vim-snippets $build_dir

cd $src_dir

find . -maxdepth 2 -type f -name "*.snippets" | while read FNAME; do mv "$FNAME" "${FNAME//.snippets/.snip}"; done

cd $src_dir

cat $list_file | xargs mv -t $snippets_dir

cp -r coffee $snippets_dir
cp -r javascript $snippets_dir

cd $neosnippets

# find . -name '*.snip' -exec sed -i 's/\t/   /g' '{}' \;
find . -name '*.snip' -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' '{}' \;

cd

rm -rf $build_dir
